export const enum ProjectNamesEnum {
  MOKUHANGA = '2025-mokuhanga',
  CAFE_SERIES = '2024-cafe-series',
  ANIMAL_WORLD = '2024-animal-world',
  MT_GRETNA_2023 = '2023-mt-gretna',
  GSHI_2022 = '2022-gshi',
  OAXACA_2022 = '2022-oaxaca',
  MARCIAS_RANCH_2020 = '2020-marcias-ranch',
  SURPRISE_ENCOUNTER = '2024-surprise-encounter',
  WORKS_ON_CARDBOARD = 'works-on-cardboard',
  BIRDS_OF_NY = 'birds-of-ny',
  PETS = 'pets',
}

/**
 * Making a fake DB here. A project has many artworks.
 */
export type Project = {
  title: string;
  description: string;
};
export type Artwork = {
  available?: boolean;
  date: string;
  description?: string;
  dimensions: string;
  image: string;
  medium: string;
  notes?: string;
  title: string;
  cost?: number;
};

export const Projects: Record<ProjectNamesEnum, Project> = {
  [ProjectNamesEnum.MOKUHANGA]: {
    title: '2025 Mokuhanga',
    description: 'This is Project A.',
  },
  [ProjectNamesEnum.CAFE_SERIES]: {
    title: '2024 Cafe series',
    description: 'This is Project B.',
  },
  [ProjectNamesEnum.ANIMAL_WORLD]: {
    title: '2024 Animal world',
    description: 'This is Project C.',
  },
  [ProjectNamesEnum.SURPRISE_ENCOUNTER]: {
    title: '2024 Surprise encounter',
    description: 'This is Project D.',
  },
  [ProjectNamesEnum.WORKS_ON_CARDBOARD]: {
    title: 'Works on cardboard',
    description: 'This is Project E.',
  },
  [ProjectNamesEnum.MT_GRETNA_2023]: {
    title: '2023 Mt Gretna',
    description: 'This is Project F.',
  },
  [ProjectNamesEnum.GSHI_2022]: {
    title: '2022 GSHI',
    description: 'This is Project G.',
  },
  [ProjectNamesEnum.BIRDS_OF_NY]: {
    title: 'Birds of NY',
    description: 'This is Project G.',
  },
  [ProjectNamesEnum.PETS]: {
    title: 'Pets',
    description: 'This is Project H.',
  },
  [ProjectNamesEnum.MARCIAS_RANCH_2020]: {
    title: 'Marcias Ranch 2020',
    description: 'This is Project I.',
  },
  [ProjectNamesEnum.OAXACA_2022]: {
    title: 'Oaxaca 2022',
    description: 'This is Project J.',
  },
};

export const Artworks: Record<ProjectNamesEnum, Artwork[]> = {
  [ProjectNamesEnum.MOKUHANGA]: [
    {
      available: true,
      date: '2024-01-01',
      description: 'This is Artwork D.',
      dimensions: '100 x 100 cm',
      image: '/2024-surprise-encounter/24-moose.jpg',
      medium: 'Oil on canvas',
      notes: 'This is a note.',
      title: 'Artwork D',
    },
    {
      available: true,
      date: '2024-01-01',
      description: 'This is Artwork D.',
      dimensions: '100 x 100 cm',
      image: '/2024-surprise-encounter/24-moose.jpg',
      medium: 'Oil on canvas',
      notes: 'This is a note.',
      title: 'Artwork D',
    },
    {
      available: true,
      date: '2024-01-01',
      description: 'This is Artwork D.',
      dimensions: '100 x 100 cm',
      image: '/2024-surprise-encounter/24-moose.jpg',
      medium: 'Oil on canvas',
      notes: 'This is a note.',
      title: 'Artwork D',
    },
  ],
  [ProjectNamesEnum.CAFE_SERIES]: [
    {
      available: true,
      date: '2024-01-01',
      description: 'This is Artwork B.',
      dimensions: '100 x 100 cm',
      image: '/images/artwork-b.jpg',
      medium: 'Oil on canvas',
      notes: 'This is a note.',
      title: 'Artwork B',
    },
  ],
  [ProjectNamesEnum.ANIMAL_WORLD]: [
    {
      available: true,
      date: '2024-01-01',
      description: 'This is Artwork C.',
      dimensions: '100 x 100 cm',
      image: '/images/artwork-c.jpg',
      medium: 'Oil on canvas',
      notes: 'This is a note.',
      title: 'Artwork C',
    },
  ],
  [ProjectNamesEnum.SURPRISE_ENCOUNTER]: [
    {
      available: true,
      date: '2024-01-01',
      description: 'This is Artwork D.',
      dimensions: '100 x 100 cm',
      image: '/images/artwork-d.jpg',
      medium: 'Oil on canvas',
      notes: 'This is a note.',
      cost: 400, // idk
      title: 'Artwork D',
    },
  ],
  [ProjectNamesEnum.WORKS_ON_CARDBOARD]: [
    {
      date: '2023-09-11',
      image: '/nyc/2023-09-11.jpg',
      medium: 'gouache on carton board',
      title: 'Figs and bar tools',
      dimensions: '6x8"',
      available: false,
    },
    {
      date: '2023-09-10',
      image: '/nyc/2023-09-10.jpg',
      title: 'First time here',
      medium: 'gouache on carton board',
      dimensions: '6x8"',
      available: true,
      cost: 125,
    },
  ],
  [ProjectNamesEnum.MT_GRETNA_2023]: [
    {
      image: '/mount-gretna/07-08-23-martha-sun.jpg',
      title: "Martha's sun",
      medium: 'watercolor & gouache on paper',
      dimensions: '8x10"',
      date: '2023-07-08',
      available: false,
    },
    {
      image: '/mount-gretna/06-01-23.jpg',
      title: 'Nature shapes',
      medium: 'watercolor & gouache on carton board',
      dimensions: '8x10"',
      date: '2023-06-01',
      available: false,
    },
    {
      image: '/mount-gretna/06-01-23-self-p.jpg',
      title: 'Self portrait',
      medium: 'oil on carton board',
      dimensions: '10x8"',
      date: '2023-06-01',
      available: false,
    },
    {
      image: '/mount-gretna/07-08-23-the-tree.jpg',
      title: 'The tree',
      medium: 'oil on carton boards',
      dimensions: '24x12.5"',
      date: '2023-07-08',
      available: true,
      cost: 240,
    },
    {
      image: '/mount-gretna/07-08-22.jpg',
      title: 'A rock and two roads',
      medium: 'oil on birch',
      dimensions: '24x24"',
      date: '2023-07-08',
      available: true,
      cost: 240,
    },
    {
      image: '/mount-gretna/07-06-23-rain.jpg',
      title: 'Inside on a rainy day',
      medium: 'oil on birch',
      dimensions: '24x24"',
      date: '2023-07-06',
      available: true,
      cost: 240,
    },
    {
      image: '/mount-gretna/06-28-23-rain.jpg',
      title: 'From under the porch on a rainy day',
      medium: 'oil on three carton boards',
      dimensions: '9x36"',
      date: '2023-06-28',
      available: true,
      cost: 240,
    },
    {
      image: '/mount-gretna/06-25-23-night.jpg',
      title: 'Night light',
      medium: 'oil on carton board',
      dimensions: '8x10"',
      date: '2023-06-25',
      available: true,
      cost: 240,
    },
    {
      image: '/mount-gretna/06-25-23-branches.jpg',
      title: 'Sticks, leaves, and moss',
      medium: 'oil on two carton boards',
      dimensions: '9x24"',
      date: '2023-06-25',
      available: true,
      cost: 240,
    },
  ],
  [ProjectNamesEnum.BIRDS_OF_NY]: [
    {
      image: '/nyc/2022-12-1-tufted-titmouse.jpg',
      title: 'Tufted titmouse',
      medium: 'watercolor on paper',
      dimensions: '10x8"',
      date: '2022-12-01',
      available: false,
    },
    {
      image: '/nyc/2022-12-1-red-winged-blackbird.jpg',
      title: 'Red winged blackbird',
      medium: 'watercolor on paper',
      dimensions: '10x8"',
      date: '2022-12-01',
      available: false,
    },
    {
      image: '/nyc/2022-12-1-oriole.jpg',
      title: 'Oriole',
      medium: 'watercolor on paper',
      dimensions: '10x8"',
      date: '2022-12-01',
      available: false,
    },
    {
      image: '/nyc/2022-12-1-northern-flicker.jpg',
      title: 'Northern flicker',
      medium: 'watercolor on paper',
      dimensions: '10x8"',
      date: '2022-12-01',
      available: false,
    },
    {
      image: '/nyc/2022-12-1-northern-cardinal.jpg',
      title: 'Northern cardinal',
      medium: 'watercolor on paper',
      dimensions: '10x8"',
      date: '2022-12-01',
      available: false,
    },
    {
      image: '/nyc/2022-12-1-eastern-bluebird.jpg',
      title: 'Eastern bluebird',
      medium: 'watercolor on paper',
      dimensions: '10x8"',
      date: '2022-12-01',
      available: false,
    },
  ],
  [ProjectNamesEnum.GSHI_2022]: [
    {
      image: '/maine/2022-6-30-neil.jpg',
      title: 'Neil, 2022',
      medium: 'pen on paper',
      dimensions: '14x11"',
      available: false,
      cost: 125,
      date: '2022-06-30',
    },
    {
      image: '/maine/2022-7-1-water-wc.jpg',
      title: 'From under the bridge',
      medium: 'watercolor on paper',
      dimensions: '18x24"',
      available: false,
      date: '2022-07-01',
      cost: 730,
    },
    {
      image: '/maine/2022-7-1-wc.jpg',
      title: 'A seal jumped for fish',
      medium: 'watercolor on paper',
      dimensions: '18x24"',
      available: false,
      date: '2022-07-01',
      cost: 730,
    },
    {
      image: '/maine/2022-6-29-wc.jpg',
      title: 'A slug sat in my palette',
      medium: 'watercolor on paper',
      dimensions: '18x24"',
      available: false,
      date: '2022-06-29',
      cost: 730,
    },
    {
      image: '/maine/2022-7-1-water-wc.jpg',
      title: 'From under the bridge',
      medium: 'watercolor on paper',
      dimensions: '18x24"',
      available: false,
      date: '2022-07-01',
      cost: 730,
    },
    {
      image: '/maine/2022-6-27.jpg',
      title: 'Great Spruce Head Island',
      medium: 'acrylic on board',
      dimensions: '12x9"',
      available: false,
      date: '2022-06-27',
    },
    {
      image: '/maine/2022-6-28.jpg',
      title: 'Great Spruce Head Island',
      medium: 'acrylic on board',
      dimensions: '12x9"',
      available: false,
      date: '2022-06-28',
      cost: 270,
    },
  ],
  [ProjectNamesEnum.PETS]: [
    {
      image: '/pets/2023-01-31-Ollie.jpg',
      title: 'Milo',
      medium: 'iPad',
      available: false,
      date: '2023-01-31',
      dimensions: 'iPad',
    },
    {
      image: '/pets/2023-01-31-Ethan.jpg',
      title: 'Ethan',
      medium: 'iPad',
      available: false,
      date: '2023-01-31',
      dimensions: 'iPad',
    },
    {
      image: '/pets/2022-5-Dean.jpg',
      title: 'Dean',
      medium: 'iPad',
      available: false,
      date: '2022-05-01',
      dimensions: 'iPad',
    },
    {
      image: '/nyc/2021-12-25.jpg',
      title: 'Miso',
      medium: 'iPad',
      available: false,
      date: '2021-12-25',
      dimensions: 'iPad',
    },
    {
      image: '/nyc/2021-12-24-xena.jpg',
      title: 'Xena',
      medium: 'iPad',
      available: false,
      date: '2021-12-24',
      dimensions: 'iPad',
    },
    {
      image: '/pets/2021-12-6-jerry.png',
      title: 'Jerry',
      medium: 'iPad',
      available: false,
      date: '2021-12-06',
      dimensions: 'iPad',
    },
    {
      image: '/pets/2020-brisket.jpg',
      title: 'Brisket',
      medium: 'watercolor on paper',
      dimensions: '14x10"',
      available: false,
      date: '2020-01-01',
    },
    {
      image: '/pets/2020-angus.jpg',
      title: 'Angus',
      medium: 'watercolor on paper',
      dimensions: '14x10"',
      available: false,
      date: '2020-01-01',
    },
    {
      image: '/marcias-ranch/2020-9-5-toby.jpg',
      title: 'Toby',
      medium: 'acrylic on board',
      dimensions: '4x4"',
      available: false,
      date: '2020-09-05',
    },
    {
      image: '/marcias-ranch/2020-9-5-eartha.jpg',
      title: 'Eartha',
      medium: 'acrylic on board',
      dimensions: '3x4"',
      available: false,
      date: '2020-09-05',
    },
  ],
  [ProjectNamesEnum.MARCIAS_RANCH_2020]: [
    {
      image: '/marcias-ranch/2020-8-14-purple-sky.JPG',
      title: 'Sunset',
      medium: 'watercolor on paper',
      dimensions: '8x11.5"',
      available: false,
      date: '2020-08-14',
    },
    {
      image: '/marcias-ranch/2020-8-14-pink-sky.JPG',
      title: 'Sunset',
      medium: 'watercolor on paper',
      dimensions: '8x11.5"',
      available: false,
      date: '2020-08-14',
    },
    {
      image: '/marcias-ranch/2020-8-14-purple-sky.JPG',
      title: 'Sunset',
      medium: 'watercolor on paper',
      dimensions: '8x11.5"',
      available: false,
      date: '2020-08-14',
    },
    {
      image: '/marcias-ranch/2020-8-14-pink-sky.JPG',
      title: 'Sunset',
      medium: 'watercolor on paper',
      dimensions: '8x11.5"',
      available: false,
      date: '2020-08-14',
    },
    {
      image: '/marcias-ranch/2020-07-16-peonies.jpg',
      title: 'Peonies',
      medium: 'acrylic on board',
      dimensions: '6x8"',
      available: true,
      date: '2020-07-16',
    },
    {
      image: '/marcias-ranch/2020-07-17-hollyhocks.jpg',
      title: 'Hollyhocks',
      medium: 'acrylic on board',
      dimensions: '6x8"',
      available: true,
      date: '2020-07-17',
    },
    {
      image: '/marcias-ranch/2020-07-18-purples.jpg',
      title: 'Purple sage',
      medium: 'acrylic on board',
      dimensions: '6x8"',
      available: false,
      date: '2020-07-18',
    },
    {
      image: '/marcias-ranch/2020-08-01-succulent.jpg',
      title: 'Succulent',
      medium: 'acrylic on board',
      dimensions: '9x12"',
      available: true,
      date: '2020-08-01',
      cost: 250,
    },
    {
      image: '/marcias-ranch/2020-8-23-clouds-mtns.jpg',
      title: 'Mountains and clouds',
      medium: 'acrylic on board',
      dimensions: '6x6"',
      available: true,
      date: '2020-08-23',
      cost: 110,
    },
    {
      image: '/marcias-ranch/2020-8-23-clouds.jpg',
      title: 'Clouds',
      medium: 'acrylic on board',
      dimensions: '6x6"',
      available: true,
      date: '2020-08-23',
      cost: 110,
    },
    {
      image: '/marcias-ranch/2020-8-23-cows.jpg',
      title: 'Cows',
      medium: 'acrylic on board',
      dimensions: '6x6"',
      available: true,
      date: '2020-08-23',
      cost: 110,
    },
    {
      image: '/marcias-ranch/2020-8-30-diptych.jpg',
      title: 'Leaves',
      medium: 'acrylic on panels',
      dimensions: '12x12"', // not right
      available: true,
      date: '2020-08-30',
    },
    {
      image: '/marcias-ranch/2020-8-31-pregnant-cow.jpg',
      title: 'Pregnant cow',
      medium: 'acrylic on board',
      dimensions: '6x8"',
      available: true,
      date: '2020-08-31',
    },
    {
      image: '/marcias-ranch/2020-9-2-pool.jpg',
      title: 'Pool',
      medium: 'acrylic on board',
      dimensions: '6x8"',
      available: false,
      date: '2020-09-02',
    },
    {
      image: '/marcias-ranch/2020-9-5-casita.jpg',
      title: 'The Casita',
      medium: 'acrylic on board',
      dimensions: '9x12"',
      available: true,
      date: '2020-09-05',
    },
    {
      image: '/marcias-ranch/2020-9-5-i-came-from-you.jpg',
      title: 'I came from you',
      medium: 'acrylic on board',
      dimensions: '9x12"',
      available: false,
      date: '2020-09-05',
    },
    {
      image: '/marcias-ranch/2020-9-7-road.jpg',
      title: 'The road',
      medium: 'acrylic on board',
      dimensions: '9x12"', // not right
      available: false,
      date: '2020-09-07',
    },
  ],
  [ProjectNamesEnum.OAXACA_2022]: [
    {
      image: '/oaxaca/2022-10-20.jpg',
      title: 'Flowers, edition of 10',
      medium: 'etching, ink on cotton',
      dimensions: '7.6x7.6"',
      available: true,
      date: '2022-10-20',
      cost: 185,
    },
    {
      image: '/oaxaca/2022-09-05.jpg',
      title: 'Bedroom at night, 2022',
      medium: 'ink on bristol',
      dimensions: '8x24"',
      available: false,
      cost: 250,
      date: '2022-09-05',
    },
    {
      image: '/oaxaca/2022-09-11.jpg',
      title: 'Untitled, 2022',
      medium: 'pen on paper',
      dimensions: '14x11"',
      available: false,
      cost: 200,
      date: '2022-09-11',
    },
    {
      image: '/oaxaca/2022-10-04.jpg',
      title: 'Buddies',
      medium: 'watercolor on paper',
      dimensions: '16x12"',
      available: true,
      cost: 400,
      date: '2022-10-04',
    },
    {
      image: '/oaxaca/2022-09-20.JPG',
      title: 'Nature sketch',
      medium: 'watercolor on paper',
      dimensions: '10x12"',
      available: false,
      date: '2022-09-20',
    },
    {
      image: '/oaxaca/2022-09-09.jpg',
      title: 'Night study',
      medium: 'watercolor on paper',
      dimensions: '16x12"',
      available: false,
      date: '2022-09-09',
    },
    {
      image: '/oaxaca/2022-09-30.jpg',
      title: 'Flowers in space, 2022',
      medium: 'acrylic on three boards',
      dimensions: '16x16"',
      available: true,
      date: '2022-09-30',
      cost: 820,
    },
    {
      image: '/oaxaca/2022-09-23.jpg',
      title: 'Flowers, 2022',
      medium: 'acrylic on two boards',
      dimensions: '10x16"',
      available: false,
      date: '2022-09-23',
    },
    {
      image: '/oaxaca/2022-09-22-corner.jpg',
      title: 'Add it to the wall series!, 2022',
      medium: 'acrylic on canvas',
      dimensions: '10x8"',
      available: false,
      date: '2022-09-22',
    },
    {
      image: '/oaxaca/2022-09-19.jpg',
      title: 'Rainy season, 2022',
      medium: 'acrylic on canvas',
      dimensions: '6x8"',
      available: true,
      date: '2022-09-19',
      cost: 150,
    },
    {
      image: '/oaxaca/2022-09-17.jpg',
      title: 'To stay, 2022',
      medium: 'acrylic on two boards',
      dimensions: '12x18"',
      available: false,
      date: '2022-09-17',
      cost: 540,
    },
    {
      image: '/oaxaca/2022-09-10.jpg',
      title: 'Night porch, 2022',
      medium: 'acrylic on two boards',
      dimensions: '8x16"',
      available: false,
      date: '2022-09-10',
      cost: 320,
    },
  ],
};

export const getArtworkPath = (artwork: Artwork) => {
  return `${artwork.date}-${artwork.title.toLowerCase().replace(/ /g, '-')}`;
};

const roseSeries: Artwork[] = [
  {
    image: '/paros-greece/2022-4-rose-series-1.jpg',
    title: 'The Ninth Rose, 1/9',
    medium: 'drypoint and watercolor on cotton',
    dimensions: '3.75x6"',
    date: '2022-04-01',
    available: true,
  },
  {
    image: '/paros-greece/2022-4-rose-series-2.jpg',
    title: 'The Ninth Rose, 2/9',
    medium: 'drypoint and watercolor on cotton',
    dimensions: '3.75x6"',
    date: '2022-04-01',
    available: true,
  },
  {
    image: '/paros-greece/2022-4-rose-series-3.jpg',
    title: 'The Ninth Rose, 3/9',
    medium: 'drypoint and watercolor on cotton',
    dimensions: '3.75x6"',
    date: '2022-04-01',
    available: true,
  },
  {
    image: '/paros-greece/2022-4-rose-series-4.jpg',
    title: 'The Ninth Rose, 4/9',
    medium: 'drypoint and watercolor on cotton',
    dimensions: '3.75x6"',
    date: '2022-04-01',
    available: false,
  },
  {
    image: '/paros-greece/2022-4-rose-series-5.jpg',
    title: 'The Ninth Rose, 5/9',
    medium: 'drypoint and watercolor on cotton',
    dimensions: '3.75x6"',
    date: '2022-04-01',
    available: false,
  },
  {
    image: '/paros-greece/2022-4-rose-series-6.jpg',
    title: 'The Ninth Rose, 6/9',
    medium: 'drypoint and watercolor on cotton',
    dimensions: '3.75x6"',
    date: '2022-04-01',
    available: true,
  },
  {
    image: '/paros-greece/2022-4-rose-series-7.jpg',
    title: 'The Ninth Rose, 7/9',
    medium: 'drypoint and watercolor on cotton',
    dimensions: '3.75x6"',
    date: '2022-04-01',
    available: true,
  },
  {
    image: '/paros-greece/2022-4-rose-series-8.jpg',
    title: 'The Ninth Rose, 8/9',
    medium: 'drypoint and watercolor on cotton',
    dimensions: '3.75x6"',
    date: '2022-04-01',
    available: false,
  },
  {
    image: '/paros-greece/2022-4-rose-series-9.jpg',
    title: 'The Ninth Rose, 9/9',
    medium: 'drypoint and watercolor on cotton',
    dimensions: '3.75x6"',
    date: '2022-04-01',
    available: true,
  },
];

const penAndPencil: Artwork[] = [
  {
    image: '/nyc/2021-09-26-roof-plants.jpg',
    title: 'Rooftop plants, 2021',
    medium: 'graphite on paper',
    dimensions: '14x17"',
    available: true,
    cost: 310,
    date: '2021-09-26',
  },
  {
    image: '/paros-greece/2022-3-27-bread.jpg',
    title: 'Holy bread, 2022',
    medium: 'graphite and gouache on gray paper',
    dimensions: '11.75x15.25"',
    available: true,
    cost: 235,
    date: '2022-03-27',
  },
  {
    image: '/paros-greece/2022-3-self-portrait.jpg',
    title: 'Self portrait, 2022',
    medium: 'graphite and gouache on gray paper',
    dimensions: '20x14.5"',
    available: false,
    cost: 235,
    date: '2022-03-27',
  },
  {
    image: '/maine/2022-6-30-neil.jpg',
    title: 'Neil, 2022',
    medium: 'pen on paper',
    dimensions: '14x11"',
    available: false,
    cost: 125,
    date: '2022-06-30',
  },
  {
    image: '/canada/2022-7-12-jimmy.jpg',
    title: 'Jimmy, 2022',
    medium: 'pen on paper',
    dimensions: '14x11"',
    available: false,
    cost: 125,
    date: '2022-07-12',
  },
  {
    image: '/canada/2022-7-12-shelley-milo.jpg',
    title: 'Shelley and Milo, 2022',
    medium: 'pen on paper',
    dimensions: '14x11"',
    available: false,
    cost: 125,
    date: '2022-07-12',
  },
  {
    image: '/nc/2022-08-23.jpg',
    title: 'The back yard, 2022',
    medium: 'ink on bristol',
    dimensions: '8x24"',
    available: false,
    cost: 250,
    date: '2022-08-23',
  },
  {
    image: '/nc/2022-08-24.jpg',
    title: 'Dry Creek Trail, 2022',
    medium: 'ink on bristol',
    dimensions: '11x24"',
    available: false,
    cost: 345,
    date: '2022-08-24',
  },
];

const miscWatercolor: Artwork[] = [
  // 2022 and earlier
  {
    image: '/nc/2022-6-18.jpg',
    title: 'The red tree again',
    medium: 'watercolor on paper',
    dimensions: '4x6"',
    available: false,
    date: '2022-06-18',
  },
  {
    image: '/nc/2022-6-17.jpg',
    title: 'The red tree',
    medium: 'watercolor on paper',
    dimensions: '4x6"',
    available: false,
    date: '2022-06-17',
  },
  {
    image: '/paros-greece/2022-2-church.jpg',
    title: 'Church',
    medium: 'watercolor on paper',
    dimensions: '9x12"',
    available: false,
    date: '2022-02-01',
  },
  {
    image: '/nc/2020-6-29-rosemary-field.jpg',
    title: "Rosemary's farm",
    medium: 'watercolor on paper',
    dimensions: '5.5x12"',
    available: false,
    date: '2020-06-29',
  },
  {
    image: '/nc/2020-5-jlo.jpg',
    title: 'North Carolina home',
    medium: 'watercolor on paper',
    dimensions: '4x6"',
    available: false,
    date: '2020-05-01',
  },
  {
    image: '/nc/2020-4-18-barn.jpg',
    title: "Rosemary's barn",
    medium: 'watercolor on paper',
    dimensions: '5x8"',
    available: false,
    date: '2020-04-18',
  },
  {
    image: '/canada/2017-canada-sketch.jpg',
    title: 'The Big House',
    medium: 'watercolor on paper',
    dimensions: '5x8"',
    available: false,
    date: '2017-01-01',
  },
];
